# .github/workflows/hello-world.yml
name: "Hello World Self-Hosted Runner"

# Workflow triggers on a push to the 'main' branch
on:
  push:
    branches:
      - master

jobs:
  hello_world:
    name: "Hello World"

    # Target your self-hosted runner
    runs-on: self-hosted

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3 # Checkout the repository

      - name: "Print Hello World."
        run: |
          echo "Hello, World! This is running on a self-hosted runner."
